- name: users | simone | create group
  tags: groups,simone,users
  group:
    name: simone
    state: present

- name: users | simone | create group
  tags: groups,simone,users
  group:
    name: ansible
    state: present

- name: users | ub | create user
  tags: ub,sudo,users
  ansible.builtin.user:
    name: simone
    group: simone
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "Ubuntu User"
    password: "{{ simone_passwd }}"
    shell: /bin/bash

- name: users | simone | create .ssh directory
  tags: dotfiles,simone,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: ub
    group: ub
    mode: 0700
  with_items:
    - { dir: '/home/simone/.ssh' }

- name: users | simone | add github key
  tags: settings,simone,sudo,system,users
  copy:
    src: users/simone/ssh/id_ed25519
    dest: /home/simone/.ssh/id_ed25519
    owner: simone
    group: simone
    mode: 0400

- name: users | simone | add github key
  tags: settings,simone,sudo,system,users
  copy:
    src: users/simone/ssh/id_ed25519.pub
    dest: /home/simone/.ssh/id_ed25519.pub
    owner: simone
    group: simone
    mode: 0444

- name: users | simone | add public key
  tags: dotfiles,simone,ssh,ssh-keys,users
  authorized_key:
    user: simone
    key: "{{ item }}"
  with_file:
    #- users/simone/ssh/simone_id_ed25519.pub
    - users/simone/ssh/ub@K53SV_id_ed25519.pub

# Copyright 2022 Google LLC.
# SPDX-License-Identifier: Apache-2.0
- name: Add github.com public keys to known_hosts
  ansible.builtin.known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: github.com
    # Download the keys from the GitHub API and prepend 'github.com' to them to
    # match the known_hosts format.
    key: |
      {% for key in (lookup('ansible.builtin.url',
                            'https://api.github.com/meta',
                            split_lines=False, validate_certs=True)
                     |from_json)['ssh_keys'] %}
      github.com {{ key }}
      {% endfor %}

- name: users | simone | add sudoers file
  tags: settings,simone,sudo,system,users
  copy:
    src: users/sudoers_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440
