
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ


set nocompatible              " be iMproved, required
filetype off                  " required for Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

"==============================================
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"=============================================
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.

" https://github.com/NLKNguyen/papercolor-theme
Plugin 'NLKNguyen/papercolor-theme'

" https://github.com/vim-airline/vim-airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'


" https://github.com/rafi/awesome-vim-colorschemes
""Plugin 'rafi/awesome-vim-colorschemes'

" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
""Plugin 'git://git.wincent.com/command-t.git'

" git repos on your local machine (i.e. when working on your own plugin)
""Plugin 'file:///home/gmarik/path/to/plugin'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
""Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"" Plugin 'ascenator/L9', {'name': 'newL9'}


""" Lang syntax

" https://github.com/NLKNguyen/c-syntax.vim
Plugin 'NLKNguyen/c-syntax.vim'
" https://github.com/elzr/vim-json
Plugin 'elzr/vim-json'
" https://github.com/Shirk/vim-gas
Plugin 'Shirk/vim-gas'
" https://github.com/vim-python/python-syntax/
Plugin 'vim-python/python-syntax'

" https://github.com/fatih/vim-go
""Plugin 'fatih/vim-go'
" https://github.com/pboettch/vim-cmake-syntax
Plugin 'pboettch/vim-cmake-syntax'


" All of your Plugins must be added before the following line
call vundle#end()            " !!!required


"======================================

filetype plugin indent on    " !!! required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"


" Put your non-Plugin stuff after this line
set path+=**
set wildmenu
set spelllang=en_us
"if has('mouse')
"  set mouse=a
"endif
set laststatus=2
set number
set ruler

nnoremap Q gqip
nnoremap S :split<Return>

"


"syntax on # it's always on for known filetypes in ubuntu vim
"colorscheme default
set t_Co=256   " This is may or may not needed.

" Light variant
set background=light
colorscheme PaperColor
" Dark variant
""set background=dark
""colorscheme PaperColor

" set vim-airline theme:
let g:airline_theme='papercolor'
"let g:lightline = { 'colorscheme': 'PaperColor' }

"" Airline fonts fallback
"" From :help airline-customization
"" for fallback if powerline fonts is missing
" air-line
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''


"========================================
" Open *.nasm files with appropriate filetype
autocmd BufRead,BufNewFile *.nasm set filetype=nasm

"Highlight trailing whitespaces
runtime custom_vimrc/.vimrc_highlight_trailing
"set encoding=utf-8
"set listchars=trail:·
"set list
" OR:
"highlight ws ctermbg=red guibg=red
"match ws /\s\+$/
"autocmd BufWinEnter * match ws /\s\+$/

